# Use the official Node 8 runtime as a parent image
FROM node:boron

# Define a NODE_ENV arg and set a default value
# Can be overridden like so docker build --build-arg NODE_ENV=someenv .
ARG NODE_ENV=development

# Define NODE_ENV environment variable
ENV NODE_ENV=${NODE_ENV}

# Set the working directory to /app
WORKDIR /app

# Copy the required files into the container at /app
# Only need to add package.json in dev mode as the node app is mounted
# as a volume with Docker Compose
COPY ["package.json", "./"]

# Install node dependencies
# http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/
RUN npm install

# Run node app when the container launches
CMD ["npm", "start"]

# Make port 3000 available to the world outside this container
EXPOSE 3000
