version: '3.0'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the node app as a volume so local changes are reflected in the container
      - ./index.js:/app/index.js
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    depends_on:
      - nodeapp
